### ISSUE TITLE
Import specification content from sourceforge

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#1]
This repository is empty and does not contain anything. 
This is confusing and landed here on the search for the specifications repository.

This repo should be updated with the specification content from sourceforge.

**Comment by mhucka** [comment]
This is where we started the work to move the specifications from sourceforge to github. It should not be deleted. Instead, we should finish the transition.

**Comment by matthiaskoenig** [comment]
I agree (just looked a bit dead after 4 years ;). It would be great to completely move the remaining sourceforge content to github. I updated the issue accordingly.

**Comment by mhucka** [comment]
I can't say I blame you! :-) This is related to the discussion we had over sbml-team in December, about handling spec issues on GitHub. I think we settled what to do about issues, so one thing we could do quickly is start using this repository for issues, while still pointing to SVN as the location of the spec files.

**Comment by luciansmith** [comment]
@matthiaskoenig @mhucka:  This is now done!  The entire codebase and issues are now fully migrated.  The only issue left is that the labels on the issues are a bit messy, but we can clean that up if need be going forward.
