### ISSUE TITLE
FBC V2 typos section 2

### ISSUE THREAD

**Issue by sbmlsecretary** [sbmlteam/sbml-specifications#289]
Reported by Robert Muetzelfeldt

There are two tiny typos in the second paragraph of section 2.1:
"It is perhaps worth noting that while SBML Level 2 does have a construct known as Constraint, its function *** traditionally limited to measuring and reporting a model variables behavior in time. "

1. "is" should be added between "function" and "traditionally"

The bit in red should either be:
"... a model variable's behavior ..."

or

"... model variables' behavior ..."  (no "a")

2) There should be a comma after "... noting that", to bracket off the subsidiary phrase "while ... Constraint".

Reported by: bgoli

Original Ticket: [sbml/sbml-specifications//289](https://sourceforge.net/p/sbml/sbml-specifications//289)

**Comment by sbmlsecretary** [comment]
- **labels**: FBC --> Level 3 Version 1 Package: fbc
- **Group**: Reported-Proposed --> Accept-formatting-and-typos


Original comment by: luciansmith

**Comment by sbmlsecretary** [comment]
Setting this to 'accept/typos' since that only needs a single editor, and Brett was the one that brought it up.

Brett, have these been fixed and released?

Original comment by: luciansmith

**Comment by sbmlsecretary** [comment]
Not yet, I am giving the specification time to settle and will deal with all reported typos in one go in a month or two.

Original comment by: bgoli

**Comment by sbmlsecretary** [comment]
What is the current status of that?

Original comment by: andreas-draeger

**Comment by sbmlsecretary** [comment]
Reported by Steffen Waldherr:

<reaction id="R4" fbc:lowerFluxBound="posInf" fbc:upperFluxBound="posInf" ... />

(page 14, line 23). Is that a typo in the lower bound, because negative infinity would seem to make more sense here?

(I'll deal with all of these in 2017 Q1)

Original comment by: bgoli

**Comment by sbmlsecretary** [comment]
Thanks for the reports these have now been corrected in the spec, revision: 25361

Original comment by: bgoli

**Comment by bgoli** [comment]
checked as fixed in current development version (https://github.com/bgoli/sbml-fbc-spec)
