### ISSUE TITLE
fbc-v3: required attribute `variableType` missing in `fluxObjective` examples

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#370]
In the latest fbc-v3 specification draft at https://raw.githubusercontent.com/bgoli/sbml-fbc-spec/main/sf_svn/spec/main.pdf most of the `fluxObjective` examples miss the required `variableType` attribute:

Section 4.1.3 & Section 4.1.4 & Section 5.2
```
<fbc:fluxObjective fbc:reaction="R2" fbc:coefficient="1"/>
-> 
<fbc:fluxObjective fbc:reaction="R2" fbc:coefficient="1" variableType="linear"/>
```

Section 5.1
```
<fbc:fluxObjective fbc:reaction="R_BiomassEcoli" fbc:coefficient="1"/>
-> 
<fbc:fluxObjective fbc:reaction="R_BiomassEcoli" fbc:coefficient="1" variableType="linear"/>
```

@bgoli I opened the issue here so Frank is also seeing this ;)

**Comment by bgoli** [comment]
@matthiaskoenig excellent thanks! I haven't systematically looked at the examples yet so this is very useful.

**Comment by bgoli** [comment]
thanks, fixed in all examples (https://github.com/bgoli/sbml-fbc-spec) will be merged with official spec repo soon
