### ISSUE TITLE
Allow lower-dimensional AnalyticVolumes

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#376]
From @jcschaff :
In VCell, we abuse the terminology a bit .. but AnalyticVolumes are also handy for 2D and 1D Geometries.   (maybe we should call it AnalyticFieldGeometry by its similarity to SampledFieldGeometry).   In VCell, for N dimensional geometries, these analytic functions are defined in the full N dimensions ... so for 3D they are defined over the whole volume, for 2D they are defined in 2D and for 1D they are defined in 1D.

Maybe we can leave it like it is - but I imagine that anyone who implements this for 3D would also want it for 2D at least - and VCell has a ton of 2D AnalyticGeometries.

**Comment by luciansmith** [comment]
Proposed new text:

"The AnalyticVolume is used to specify the analytic expression of a domain. The analytic expression for the Analyt-icVolume is defined in the Math element. Despite the word ’volume’ in the name, an AnalyticVolume may be defined for geometries of any dimension. The only difference is that the Math of an AnalyticVolume for a 3-dimensional geometry will contain references to the three CoordinateComponent axes (i.e. “x”, “y”, and “z”), but will contain fewer for lower-dimensional geometries."

**Comment by jcschaff** [comment]
Hi Lucian - thanks.  The new text looks good (except the typo
"Analyt-icVolume").

Best regards,
Jim.
