### ISSUE TITLE
fbc-v3: word missing in sentence about UserDefinedConstraint

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#378]
In section 3.14 (page 18, L40f) a word is missing in the following sentence.
> In order to achieve we defined a new type of linear constraint, the UserDefinedConstraint.

Should be
>In order to achieve that a new type of constraint was defined, the UserDefinedConstraint.

* fixed missing word
* better passive than active sentence
* the `linear` is probably incorrect so I would leave it out to avoid confusion, because the `variableType` can also be `quadratic` (a linear combination of quadratic terms ;)

**Comment by bgoli** [comment]
Thanks, this has been corrected in (https://github.com/bgoli/sbml-fbc-spec) which will be merged here soon
