### ISSUE TITLE
fbc-v3: UserDefinedConstraintComponent coefficient defined as double in UML

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#379]
@fbergmann @bgoli 
In Figure 10 the `coefficient` of the `UserDefinedConstraintComponent` is defined as a `double` (see below)
![image](https://user-images.githubusercontent.com/900538/179850794-11a74b4f-905a-4740-b60a-fba179bc058f.png)

But in the text and examples the coefficient is defined as an `SIdRef` to a constant parameter:
> The coefficient attribute
> The required coefficient attribute contains an SIdRef that is restricted to reference only a constant which holds the coefficient value. In strict mode a Parameter whose SId is referenced by a coefficient, as in the case of a FluxObjective coefficient, has to be constant and not take the value NaN or ±inf.

![image](https://user-images.githubusercontent.com/900538/179851644-7b88c27e-4f41-4d41-9f17-9353b5ca9dc9.png)

This discrepancy has to be resolved.

I don't see any reason why the coefficient of the UserDefinedConstraint has to reference a parameter. The coefficient should just be a double for consistency with the `FluxObjective` and to reduce complexity in the model. Due to the need to define parameters for every coefficient the model size explodes (important for large FBC models) and things become more complicated to parse and write.
I see the special use case where one wants a changing/non-constant coefficient, but one could achieve this via defining a new variable. I.e. 
`coefficient1 * variable1` can be replaced with `1.0 * variable2` and the AssignmentRule `variable2 = coefficient1 * variable1`. We have via AssignmentRules all the complexity already in SBML and don't have to replicate it in the coefficient.

My suggestion is: The coefficent of the UserDefinedConstraintComponent should be a double in line with the FluxObjective.
As a side note: 99.9% of use cases are constant coefficients, this should be encodable as simple as possible.

**Comment by matthiaskoenig** [comment]
libsbml already implements the coefficient as a double. So the description of the `coefficient` is incorrect and the example is incorrect. The specification should be updated accordingly, i.e. state that the coefficient is a double. Here how the example should look like (also the RGDP SIdRef was incorrect in the previous example):
```xml
    <listOfParameters>                                                                                                                             
      <parameter id="uc1" value="5" constant="true"/>                                                                                              
      <parameter id="uc2lb" value="2" constant="true"/>                                                                                            
      <parameter id="uc2ub" value="INF" constant="true"/>                                                                                          
      <parameter id="Avar" value="NaN" constant="false"/>                                                                                           
    </listOfParameters>                                                                                                                                                                                                                                                 
    <fbc:listOfUserDefinedConstraints>                                                                                                             
      <fbc:userDefinedConstraint fbc:lowerBound="uc1" fbc:upperBound="uc1">                                                                        
        <fbc:listOfUserDefinedConstraintComponents>                                                                                                
          <fbc:userDefinedConstraintComponent fbc:coefficient="1" fbc:variable="RGLX" fbc:variableType="linear"/>                                  
          <fbc:userDefinedConstraintComponent fbc:coefficient="-1" fbc:variable="RXLG" fbc:variableType="linear"/>                                 
        </fbc:listOfUserDefinedConstraintComponents>                                                                                               
      </fbc:userDefinedConstraint>                                                                                                                 
      <fbc:userDefinedConstraint fbc:lowerBound="uc2lb" fbc:upperBound="uc2ub">                                                                    
        <fbc:listOfUserDefinedConstraintComponents>                                                                                                
          <fbc:userDefinedConstraintComponent fbc:coefficient="2" fbc:variable="Avar" fbc:variableType="linear"/>                                  
          <fbc:userDefinedConstraintComponent fbc:coefficient="-1" fbc:variable="RGDP" fbc:variableType="linear"/>                                 
        </fbc:listOfUserDefinedConstraintComponents>                                                                                               
      </fbc:userDefinedConstraint>                                                                                                                 
    </fbc:listOfUserDefinedConstraints> 
```

**edit** fixed Avar  constant=false

**Comment by bgoli** [comment]
Thanks, I think it could have been suggested to make defining MILPs easier, for example, when using a big M value (a standard method in MILP's for encoding absolute values where you get things like (J1 is a flux and Par_bin1 is a binary artificial variable): 
```
# Constraints defining an artificial variable |J1|
1.0*Par_J1abs - 1.0*J1 - bigM*Par_bin1 <= 0
1.0*Par_J1abs + 1.0*J1 + bigM*Par_bin1 <= bigM
```
bigM appears as a static coefficient in every set of absolute value constraints and might not be recognised as such if encoded as a double (and not changed in a coordinated way). 

While, as you mention, you can do this with Assignment Rules the question is "do you expect all FBC software to fully support the arbitrary math of the assignment rules for a basic MILP functionality?" 

This may also be useful for encoding coupling constraints in ME models. I'll try look up some of the original discussions to see if there were other reasons.

(Edit. in hindsight this is not a good example to use, I've updated the text to at least show a more familiar version of the same not-so-good example. The point is here anytime you want to use a model parameter bigM, Vmax, Keq as a coefficient in multiple constraints and constraint components, then you need to reference a parameter, also annotation etc etc).

**Comment by matthiaskoenig** [comment]
* I think almost nobody wants to implement problems with changing coefficients. In case somebody wanted they would have to implement the MathML and AssignmentRules solution (so it could be done, but I don't see too many practical applications).
* The MILP problem could be solved by just adding a new `variableType = milp` to indicate the milp parts in the constraint. Because the MILP variable is an artificial variable it makes a lot of sense to distinguish the MILP part from the other `coeffiecient*variable` parts in the constraints. This could even allow for `variable=None` on a component with `variableType=milp`, otherwise one has to introduce and deal with the artificial milp variable.

So my proposal would be: Keep the coefficient a double and introduce a new `variableType=milp` which can occur in a constraint nt in combination with other components of `variableType=linear`. This would allow simple encoding/parsing of MILPS without too much complexity due to all the parameters.

**Comment by bgoli** [comment]
> I think almost nobody wants to implement problems with changing coefficients.

Not as variables but in the problem definition, especially when you have the same coefficient in multiple linear constraints. M, in the problem, is constant when solving but needs to be recognised as M in all constraints. That's why in the text and examples the parameter that the coefficient points to must be set as constant, otherwise you can get a non-linear term

>  In case somebody wanted they would have to implement the MathML and AssignmentRules solution (so it could be done, but I don't see too many practical applications). 

So strict must set to false and a tool must implement mathML to essentially define a parameter that can be used in multiple constraints? If I remember correctly ME coupling constraints use Vmax's and Km's in multiple constraints, if so, it might be more difficult to encode those models as you would loose the easy relation between the model parameters in different constraints. 

> The MILP problem could be solved by just adding a new variableType = milp 

No this is not the problem. The problem is defining a single thing (a model parameter) multiple times (as multiple doubles). The variable can always either be a Reaction or a Parameter so there is nothing to distinguish.

The question is do we want these UserDefinedConstraints to encode linear problems plus trivial linear constraints, or, be more generic so that they can deal with more complex models that may arise with ME, RBA, XYZ problems?

**Comment by bgoli** [comment]
Hi @matthiaskoenig I found the HARMONY document from 2020, an interesting [question](https://docs.google.com/document/d/1ploBO3DgEzDaNK_F5Kv1t2FAxPjYzOurVJbZT9XTr34/edit?disco=AAAAJMh0lMw) was raised which, at the time, did not get much of a response. Incidentally I will also be using that text in the spec.

Remember I have to "represent" the specification in these discussions but to me this definitely a borderline case where we need to evaluate in terms of current and future cost-benefit.

Edit. I propose to think about it for a day or two, discuss it with anyone else that may be interested and then have a short online brainstorm session.

**Comment by bgoli** [comment]
@matthiaskoenig after looking at the notes of previous meetings and careful consideration I must put this down to a typo in the UML. The use of a Sid for both coefficient and variable value has been part of the UserDefinedConstraint since its initial definition and turning it into a double means a loss of potential functionality for no real gain (other than a few extra parameter definitions and associated lines of XML). The UserDefinedConstraint is an advanced, forward looking feature that has no effect on all current FBCv2 models in terms of SBML encoding.

The UserDefinedConstraint remains consistent with the other FBCv2 defined constraint definition, the upper/lower bound which also uses a Sid to point to its coefficient term and gains all the associated advantages of grouping, annotation, etc.

@fbergmann I have updated the UML so that it is now consistent with the text.

**Comment by matthiaskoenig** [comment]
Perfect. This solves this issue. Very happy with the solution.
