### ISSUE TITLE
Spatial: Clarify work with other packages

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#384]
From @matthiaskoenig : 
Some section about how spatial works/doesn’t work with other packages would be great.

I could assume that often Geometries should be coupled to existing models. The comp package would be a great application for that. It would be great if there could be an example adding a Geometry to an existing model using comp. This would also demonstrate the interoperability of comp and spatial.

How does spatial work with qual? I assume there has to be an extension of the transitions and qualitative species. This is out of the scope of this version, but there should be a sentence mentioning this.

How does spatial work with multi? I assume there has to be an extension of the multi objects. This is probably out of the scope of this version, but there should be a sentence mentioning this.

**Comment by fbergmann** [comment]
i think that is outside the scope of spatial v1. For now it does not interract with other packages, there are no implementations that do so.

**Comment by luciansmith** [comment]
Here's my write-up of spatial interactions with other packages.  It's a whole new section:

5 Interaction with other packages 
The SBML Spatial package was designed to be orthogonal to other SBML packages, and as such should interact 
freely with all of them. However, there are no current implementations that take use of these interactions, so the 
following descriptions should all be taken as guidelines for future development, and do not represent established 
protocols at this time. 
5.1 SBML Level 3 Version 2 
This package may be used with either SBML Level 3 Version 1 Core, or SBML Level 3 Version 2 Core, with no essential 
change in functionality. SBML L3v2 adds an ’id’ and ’name’ to all constructs, so a few more Spatial elements that 
don’t currently have an id would gain one. Those ids would fall in the SId namespace and not interact with the rest 
of the Spatial package. 
Even though Level 3 Version 2 elements may reference package elements in the SId namespace with mathematical 
meaning, it is impossible to do this with Spatial elements, as the ids of all elements with mathematical meaning are 
in the SpId namespace instead. Both versions of SBML Level 3 should handle this the same way. 
5.2 The comp package 
The Hierarchical Model Composition package allows models to be composed hierarchically, with submodels 
that become part of the containing model, and connections that define how to integrate the submodels into the 
containing model. Spatial models may be composed in this way just like other SBML constructs, with the caveat 
that because Spatial ids are in the SpId namespace, and because comp does not come with an element of type 
SpIdRef, metaids must be used instead. 
Also, since there may only be a single Geometry object child of the Model, the Geometry of any child submodel 
must be integrated into the parent model’s Geometry: the id, name, and coordinateSystem of the parent remains 
unchanged, and the children of the Geometry should be merged into the parent Geometry in much the same way 
that the children of the child Model are merged into the parent Model. 
5.3 The distrib package 
The Distributions package allows modelers to include new MathML csymbol contructs that define draws from 
distributions, and the ability to define the uncertainty in any element with mathematical meaning. Both could be 
employed as-is by users of the Spatial package: the csymbol constructs can be used in spatial MathML, and in core 
MathML to affect spatial elements through the SpatialSymbolReference link, and any element with mathematical 
meaning could be given an Uncertainty child defining its uncertainty. 
5.4 The multi package 
The Multistate and Multicomponent package allows modelers to define template species and reactions that are only 
realized upon actually simulating the model. In principle, the extended Species and Reaction objects defined in 
that package should be able to be placed in a spatial context. 
The work involved in interpreting and simulating such a model would be substantial, however, and more research 
needs to be done to identify best practices in using the two packages together. 
5.5 The qual package 
The Qualitative Models package allows modelers to define interaction networks that are defined by element state 
instead of element levels. In principle, such state transition modeling could be modeled in a spatially-distinguished 
context, but no effort has been made to do so at this time. Mechanically, new extensions would have to be created 
to allow the QualitativeSpecies and Transition elements from the qual package to be spatially defined before any 
such model definitions could be created. 
5.6 The layout and render packages 
The Layout Package and the Render Package allow the visualization of SBML models. In principle, both could 
be used as-is to display the underlying reaction networks being used in a spatial model. However, there are no 
special constructs available to visualize the geometry defined in the spatial package: simulators typically display this 
geometry to the user with species levels superimposed, but nothing in layout or render would help the simulator 
displaying this information. Thus, at present, the Geometry itself is used for visualization of spatial simulations, 
while layout and render are used separately to visualize the reaction network.

**Comment by fbergmann** [comment]
> 5.3 The distrib package
> The Distributions package allows modelers to include new MathML csymbol contructs that define draws from

that should be csymbol `constructs `. 

otherwise i'm fine with the section.

**Comment by luciansmith** [comment]
Done!  Thanks.

**Comment by luciansmith** [comment]
Closing this; I think we're good.

**Comment by matthiaskoenig** [comment]
Yes, this is perfect.
