### ISSUE TITLE
fbc-v3: Add example for polymer reaction to demonstrate new formula syntax

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#389]
I will fill this out later:

**Comment by skeating** [comment]
@matthiaskoenig is this something you can do or can you give me an example so I can do it

**Comment by bgoli** [comment]
I think this is now addressed in newer versions of the draft e.g. #404  Table 2 on Page 10?

**Comment by matthiaskoenig** [comment]
@skeating Sorry, I missed this issue and never filled it out correctly. Thanks for figuring this out.

**Comment by bgoli** [comment]
thanks all
