### ISSUE TITLE
Dead link to SBML specification on website

### ISSUE THREAD

**Issue by shoepfl** [sbmlteam/sbml-specifications#391]
Hi there,

the link to the SBML specification on the official website is not working anymore.
It would be cool if this could be fixed.

If you click on Specification here:
[https://sbml.org/documents/specifications/](url)
Or the broken link directly:
[http://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2](url)

also the links to the former SBML level specifications are not working anymore.

Best,
Sebastian

**Comment by matthiaskoenig** [comment]
Hi @shoepfl,

unfortunately the server went down which hosts the specification links without a fast way for recovery. 
You can find a copy of the specification via the JIB publication: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6798823/pdf/jib-16-20190021.pdf

We trying to find a quick solution for the issue hosting the specifications via github.
Best Matthias

**Comment by shoepfl** [comment]
Hi Matthias,

thanks for the fast response.
I found the specification, but just thought it is not so nice for the user experience ;)

Best,
Sebastian

**Comment by matthiaskoenig** [comment]
These links work from the official webpage and have been fixed a while back. This issue can be closed.

**Comment by luciansmith** [comment]
Thanks!
