### ISSUE TITLE
fbc-v3: Add orcid to authors, remove thanking of authors

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-specifications#394]
Some smaller things noticed by @draeger.
- it would be great if we could add orcid ids to the authors on the specification. The emails will stop working at some point but orcid ids are more persistent. Also the specification would be linked to the orcid entry
- check if Frank's affiliation at CalTech is correct
- on page 42 we thank some of the authors. We should not thank the authors, but only people not on the author list.

**Comment by fbergmann** [comment]
@matthiaskoenig my affiliation should be "BioQUANT, Heidelberg University, Heidelberg, Germany" instead of Caltech now. my orcid is 0000-0001-5553-4702

**Comment by matthiaskoenig** [comment]
Here the other changes:
- Matthias König, koenigmx@hu-berlin.de, 0000-0003-1725-179X
- Sarah Keating, 0000-0002-3356-3542
- Brett Olivier, 0000-0002-5293-5321

Where is the latest tex file for the specification, then I can make a pull request with the updates?

**Comment by luciansmith** [comment]
Latest tex at https://github.com/sbmlteam/sbml-specifications/tree/release/sbml-level-3/version-1/fbc/spec
