### ISSUE TITLE
fbc-v3: missing references

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#395]
The intro paragraph in section 1 has missing references

Genome Scale Metabolic Reconstructions (GSR’s; ?)

Level 2 or Level 3 core specification (??)

(This in https://github.com/sbmlteam/sbml-specifications/blob/develop/sbml-level-3/version-1/fbc/spec/sbml-fbc-version-3-rc2.pdf )

**Comment by luciansmith** [comment]
1.1 SBML issue tracking system (?)

**Comment by luciansmith** [comment]
2.1:  COBRA toolbox (?)

**Comment by luciansmith** [comment]
3.2  XML Schema 1.0 data types (?).

**Comment by luciansmith** [comment]
1.4: UML 1.0 (Unified Modeling Language; ??)

**Comment by luciansmith** [comment]
1.4 XML Schema 1.0 (???),

**Comment by luciansmith** [comment]
3.4  Hill system (see Table 1) (??).

**Comment by luciansmith** [comment]
3.9 BiGG database E. coli reconstruction (iJR904; ??)

**Comment by luciansmith** [comment]
4.1 SBW Flux Balance FBC implementation and CBMPy (??).

**Comment by luciansmith** [comment]
5.1 COBRA SBML Level 2 Version 1 format (???)

**Comment by luciansmith** [comment]
fbc 20204: (Reference: SBML Level 3 Specification for Flux Balance Constraints, Version 3, ?? on page ??.)

**Comment by skeating** [comment]
these look like the bibliography file wasn't picked up when generating the pdf

**Comment by bgoli** [comment]
Yip bibtex wasn't run, fixed in #402 and #404 (main.pdf)
