### ISSUE TITLE
FBC l3: ListOfKeyValuePairs should be listed as optional in UML

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#397]
The UML in figure 1 and Figure 11 does not show ListOfKeyValuePairs as being optional (i.e. '0,1' on the line from Annotations to it in the figure.)

This is assuming it is indeed optional, but I can't imagine it not being so.

**Comment by skeating** [comment]
again this requires the source for the images which is not in git

**Comment by bgoli** [comment]
Closing as changes seem acceptable
