### ISSUE TITLE
fbc v3: DocumentConventions don't say why things are red

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#400]
Section 1.4 should say that red bits are new to this spec from the previous version.

**Comment by bgoli** [comment]
Thanks for the remined to remove it from the UML/text. The red text is technically made available for for editors/authors and will become normal, black, text in the release version.

**Comment by luciansmith** [comment]
We've published other partially-red documents in JIB before, to show the difference between the current and previous versions.

**Comment by bgoli** [comment]
I find it visually offensive and remove it in final versions.

**Comment by luciansmith** [comment]
Heh.  Fair enough!
